DELETE FROM `{pre}touch_nav`;
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '店铺街', 1, 1, 0, 'store.html', 'top', 'store.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '品牌街', 1, 2, 0, 'brand.html', 'top', 'brand.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '促销活动', 1, 3, 0, 'activity.html', 'top', 'activity.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '最新团购', 1, 4, 0, 'groupbuy.html', 'top', 'groupbuy.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '积分换购', 1, 5, 0, 'exchange.html', 'top', 'exchange.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '微社区', 1, 6, 0, 'circle.html', 'top', 'community.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`) VALUES ('', 0, '微筹', 1, 7, 0, 'crowd_funding.html', 'top', 'crowd_funding.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '拍卖活动', 1, 8, 0, 'auction.html', 'top', 'auction.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '超值礼包', 1, 9, 0, 'package.html', 'top', 'package.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '专题汇', 1, 10, 0, 'topic.html', 'top', 'topic.png');